### ISSUE TITLE
Bring back DDACTS on test and alter rollup table

### ISSUE THREAD

**Issue by steveoh** [agrc/Crash-db#3]
Will you bring back the DDACTS db in test. It can be brought back from a recent production backup.

Will you also add these 4 new fields to the rollup table

```sql
ALTER TABLE [Rollup](
    [solo] [bit] NULL,
    [distracted] [bit] NULL,
    [drowsy] [bit] NULL,
    [offroad] [bit] NULL,
...
```

**Comment by MichaelAGRC** [comment]
This is done.

**Comment by steveoh** [comment]
@MichaelAGRC Did the alter table drop all of the data or was that ok to be done in without side affects?

**Comment by MichaelAGRC** [comment]
Should be okay, as they were null-able fields.
